app/models.py
"""Contain the models for the database"""

from datetime import datetime

from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

from app import db, login



class User(UserMixin, db.Model):
    """Class representing an user"""
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(130))

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        """Generate an hash to save password"""
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        """Check the hash of the password with the hash in db"""
        return check_password_hash(self.password_hash, password)

@login.user_loader
def load_user(id):
    """Use by the user for connexion"""
    return User.query.get(int(id))

class City(db.Model):
    """Class used to stock the cities searched by users"""
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), index=True)
    lat = db.Column(db.Float)
    lon = db.Column(db.Float)


class UserSearch(db.Model):
    """Class used to stock the searches for an user"""
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), primary_key=True)
    city_id = db.Column(db.Integer, db.ForeignKey('city.id'), primary_key=True)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow())
    count = db.Column(db.Integer, index=True)

app/forms.py
"""File containing all forms used in the application"""
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

from app.models import User

class LocationForm(FlaskForm):
	"""Form used for the city search"""
	location = StringField('Location', validators=[DataRequired()])
	submit = SubmitField('Chercher le lieu')

class LoginForm(FlaskForm):
	"""Form used for loging"""
	email = StringField('Identifiant', validators=[DataRequired(), Email()])
	password = PasswordField('Mot de passe', validators=[DataRequired()])
	remember_me = BooleanField('Se souvenir de moi')
	submit = SubmitField('Connexion')

class RegistrationForm(FlaskForm):
	"""Form used for Registration"""
	username = StringField('Identifiant', validators=[DataRequired()])
	email = StringField('Email', validators=[DataRequired(), Email()])
	password = PasswordField('Mot de passe', validators=[DataRequired()])
	password_confirm = PasswordField('Confirmation mot de passe', validators=[DataRequired(), EqualTo('password')])
	submit = SubmitField('S\'inscrire')

	def validate_username(self, username):
		user = User.query.filter_by(username=username.data).first()
		if user is not None:
			raise ValidationError('Ce nom d\'utilisateur est déjà utilisé.')

	def validate_email(self, email):
		user = User.query.filter_by(email=email.data).first()
		if user is not None:
			raise ValidationError('Cette adresse email est déjà utilisée.')
	

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager


db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    return app

from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
import arrow

from flask import render_template, request, redirect, url_for, flash, current_app
from flask_login import current_user, login_user, logout_user, login_required

from app.main import bp
from app import db
from app import utils
from app.forms import LocationForm, LoginForm, RegistrationForm
from app.models import User, City, UserSearch

@bp.route('/')
@bp.route("/index")
def index():
    """Main page"""
    form = LocationForm()
    return render_template('index.html', form=form)


@bp.route('/result', methods=['POST'])
def result():
    """View used to display result of the users search"""
    city = request.form['location']
    city = city.replace(' ', '-').lower() #modify string to avoid error with the APIs.
    try:
        lat, lon, meteo_data = utils.get_meteo_for_city(city)
        tides_data = utils.get_tides_for_city(lat, lon)
    except KeyError:
        flash('Aucun résultat pour la ville cherchée, essayez une autre ville.')
        return redirect(url_for('main.index'))
    if current_user.is_authenticated:
        utils.save_user_search(current_user.id, city, lat, lon)
    return render_template('result.html', meteo=meteo_data, city=city.upper(), \
                                tides=tides_data, lat=lat, lon=lon)

@bp.route('/about')
def about():
    """Display information about FishingDay project"""
    return render_template('about.html')

@bp.route('/legal')
def legal():
    """Display legal informations"""
    return render_template('legal.html')

@bp.route('/login', methods=['GET', 'POST'])
def login():
    """View used for the users to loging in"""
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Utilisateur inconnu ou mot de passe incorrect')
            return redirect(url_for('main.login'))
        login_user(user, remember=form.remember_me.data)
        return redirect(url_for('main.index'))
    return render_template('login.html', form=form)

@bp.route('/logout')
def logout():
    """View used to logout user"""
    logout_user()
    return redirect(url_for('main.index'))

@bp.route('/register', methods=['GET', 'POST'])
def register():
    """View used by users to create account"""
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Merci pour votre inscription !')
        login_user(user)
        return redirect(url_for('main.index'))
    return render_template('register.html', form=form)


@bp.route('/account')
@login_required
def account():
    """View used to display user account informations"""
    #Create 3 empty lists to stock the lasts views, the favorites cities and all the cities
    last_cities = []
    favorites_cities = []
    all_cities = []
    #Search the 5 lasts cities searched and add it to the list
    last_searches = UserSearch.query.filter_by(user_id=current_user.id).order_by(\
                    UserSearch.timestamp.desc()).limit(5).all()
    for search in last_searches:
        city = City.query.get(search.city_id)
        date = arrow.get(search.timestamp).to('Europe/Paris')
        last_cities.append({'city': city, 'date': date.strftime('%d/%m/%y à %H:%M')})
    #Search the 5 most searched cities and add it to the list
    favorites_search = UserSearch.query.filter_by(user_id=current_user.id).order_by(\
                        UserSearch.count.desc()).limit(5).all()
    for search in favorites_search:
        city = City.query.get(search.city_id)
        count = search.count
        favorites_cities.append({'city': city, 'count': count})
    #Get all search to display it on a map
    all_searches = UserSearch.query.filter_by(user_id=current_user.id).all()
    for search in all_searches:
        city = City.query.get(search.city_id)
        all_cities.append(city)
    return render_template('account.html', last_cities=last_cities, \
                            favorites_cities=favorites_cities, all_cities=all_cities, \
                            google_key=current_app.config['MAPS_API_KEY'])

app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<header class="standard-header">
	<div class="container">
		
	</div>
</header>

<section class="my-auto" id="about">
  <div class="container text-center mt-2 pt-5">
  	<h2><u>À propos</u></h2>
  	<p>FishingDay est une application web réalisée dans le cadre d'un projet étudiant. <br/>
  	Cette application a pour vocation de donner des informations utiles afin de préparer une sortie de pêche en mer. <br/>
  	Des améliorations seront surement apportées avec le temps.</p>
    <p>FishingDay est encore en construction et nécéssite donc d'être utilisé avec précaution et sens critiques. <br/>
      Les données indiquées ne sont pas toujours exactes et ne doivent donc en aucun cas être utilisées pour la navigation. <br/>
      L'équipe du site se dégage de toute responsabilité concernant l'utilisation faite des données affichées par FishingDay.
    </p>
    <hr width="50%"></hr>
    <h2>Contact</h2>
    <p>Pour toute question ou demande, vous pouvez nous écrire à l'adresse suivante : <a href="mailto:fishingday@gmail.com">fishingday@gmail.com</a>.</p>
  </div>
	
</section>

{% endblock %}

app/templates/account.html
{% extends 'base.html' %}

{% block content %}

<header class="standard-header">
	<div class="container">
		
	</div>
</header>

<section class="" id="account">
  <div class="col-lg-12 mx-auto pt-4">

  	<h1 class="text-center">{{ current_user.username }}</h1>

    <div class="row my-5 mx-3">
      <div class="col-lg-6 table-search-result">
        <div class="col-lg-12 user-result mx-auto" id="favorites-searches">
          <h2><u>Mes spots favoris : </u></h2>
          <div class="table-responsive">
            <table class="table">
              <tbody>
                {% for city in favorites_cities %}
                    <tr style="background-color: rgba(133, 193, 223, {{ (loop.index + 2)/10 }});">
                  <td>
                    <form action="{{ url_for('main.result') }}" method="post">
                      <input type="hidden" name="location" value="{{ city['city'].name }}">
                      <input type="submit" value="{{ city['city'].name.upper() }}" class="favorite-link">
                    </form>
                  </td>
                  <td class="text-center">Recherché {{ city['count'] }} fois.</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <div class="row mx-auto mt-2">
          <div class="col-lg-12 user-result" id="lasts-searches">
            <h2><u>Dernières recherches : </u></h2>
            <div class="table-responsive">
              <table class="table">
                <tbody>
                  {% for city in last_cities %}
                    <tr style="background-color: rgba(133, 193, 223, {{ (7 - loop.index)/10 }});">
                      <td>
                        <form action="{{ url_for('main.result') }}" method="post">
                          <input type="hidden" name="location" value="{{ city['city'].name }}">
                          <input type="submit" value="{{ city['city'].name.upper() }}" class="favorite-link">
                        </form>
                      </td>
                      <td class="text-center">Le {{city['date']}}</td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
        <div class="col-lg-6 map-favorites">
          <h2 class="text-center"><u>Toutes mes recherches : </u></h2>
          <div id="map"></div>
        </div>
    </div>
  </div>
</section>

<script>

// Initialize and add the map
function initMap() {

  // The map, centered on the middle of France
  var map = new google.maps.Map(
    document.getElementById('map'), {zoom: 6, center: {lat:46.36, lng: 1.30}});

  //Create a list of objects with all the cities lat and lon
  list_cities = [];

  {% for city in all_cities %}
  var city = {lat: {{ city.lat }}, lng: {{ city.lon }} };
  list_cities.push(city);
  {% endfor %}

  //Browse the list to display marker on the map
  for (var city in list_cities){
    var marker = new google.maps.Marker({position: list_cities[city], map: map});
  }

}

</script>

<script async defer
src="https://maps.googleapis.com/maps/api/js?key={{ google_key }}&callback=initMap">
</script>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="fishing - meteo - tides - map">
    <meta name="author" content="Ronan LE HAY">
    <meta name="google-site-verification" content="d_RoDv7hhctaxUZcp7w29NLszkFSp6Nqt6Ga_wyfLLw" />
    <link rel="icon" href="{{url_for('static', filename='img/fishing.png') }}">

    <title>FishingDay - Préparez votre sortie pêche</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{url_for('static', filename='css/grayscale.css') }}" rel="stylesheet">

    {% block head %}{% endblock %}

  </head>

  <body id="page-top">

  <div id="main-container">
    
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{{ url_for('main.index') }}">FishingDay</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            {% if current_user.is_anonymous %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.login') }}">Se connecter</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.register') }}">S'inscrire</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.account') }}">Mon compte</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.logout') }}">Deconnexion</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>


  {% block content %}{% endblock %}
    <div id="push-footer">
      
    </div>
  </div>
    <!-- Footer -->
    <footer class="small text-center text-white-50">
      <div>
        <a class="footer-link separator" href="https://github.com/NanroYahel/P13_FishingDay">Améliorer le projet</a>
        <a class="footer-link separator" href="{{ url_for('main.about') }}">À propos</a>
        <a class="footer-link" href="{{ url_for('main.legal') }}">Mentions légales</a>
      </div>
      <div class="container">
        Copyright &copy; FishingDay 2018
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- Plugin JavaScript -->
    <script src="{{ url_for('static', filename='vendor/font-awesome/js/all.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>

    <!-- Custom scripts for this template -->
    <script src="{{ url_for('static', filename='js/grayscale.min.js') }}"></script>

  </body>

</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

<!-- Header -->
<header class="masthead">
  <div class="container d-flex h-100 align-items-center">
    <div class="mx-auto text-center"  id="zoneTitre">
      <h1 class="mx-auto my-0 text-uppercase">Fishing Day</h1>
      <h2 class="mx-auto mt-1 mb-4">Mettez toutes les chances de votre côté !</h2>
      <form class="form-inline d-flex mb-2" method="post" action="{{ url_for('main.result') }}">
        <!-- <input type="text" class="form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0" id="inputSearch" placeholder="Où voulez-vous pêcher ? " method="post" name="location"> -->
        {{ form.hidden_tag() }}
        {{ form.location(class="form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0", placeholder="Où voulez-vous pêcher ? ") }}
        {{form.submit(class="btn btn-primary js-scroll-trigger")}}
      </form>

      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
          <p class="form-error">{{ message }}</p>
          {% endfor %}
        {% endif %}
      {% endwith %}

    </div>
  </div>
</header>

<div id="container">
<!-- Projects Section -->
<section id="projects" class="projects-section bg-light">
  <div class="container">

    <div class="row justify-content-center">
      <div class="col-lg-12">
        <h2 class="text-center mb-5">FishingDay vous fourni les informations essentielles pour votre session de pêche en mer : </h2>
      </div>
    </div>

    <!-- Project One Row -->
    <div class="row justify-content-center no-gutters mb-1 mb-lg-0">
      <div class="col-lg-6 my-auto mx-auto">
        <img class="img-fluid" src="{{ url_for('static', filename='img/meteo.png') }}" alt="">
      </div>
      <div class="col-lg-6">
        <div class="bg-project text-center h-100 project">
          <div class="d-flex h-100">
            <div class="project-text w-100 my-auto text-center text-lg-left">
              <h4 class="text-white">Meteo</h4>
              <p class="mb-0 text-white-50">L'essentiel de la météo du jour : Ensoleillement, température, direction du vent...</p>
              <hr class="d-none d-lg-block mb-0 ml-0">
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Project Two Row -->
    <div class="row justify-content-center no-gutters mb-1 mb-lg-0">
      <div class="col-lg-6 my-auto mx-auto">
        <img class="img-fluid" src="{{ url_for('static', filename='img/tides.png') }}" alt="">
      </div>
      <div class="col-lg-6 order-lg-first">
        <div class="bg-project text-center h-100 project">
          <div class="d-flex h-100">
            <div class="project-text w-100 my-auto text-center text-lg-right">
              <h4 class="text-white">Marée</h4>
              <p class="mb-0 text-white-50">Les horaires des marées.</p>
              <hr class="d-none d-lg-block mb-0 mr-0">
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Project Three Row -->
    <div class="row justify-content-center no-gutters mb-1 mb-lg-0">
      <div class="col-lg-6 mx-auto my-auto mx-auto">
        <img class="img-fluid" src="{{ url_for('static', filename='img/map.png') }}" alt="">
      </div>
      <div class="col-lg-6">
        <div class="bg-project text-center h-100 project">
          <div class="d-flex h-100">
            <div class="project-text w-100 my-auto text-center text-lg-left">
              <h4 class="text-white">Fonds Marins</h4>
              <p class="mb-0 text-white-50">La topographie marine de la zone.</p>
              <hr class="d-none d-lg-block mb-0 ml-0">
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</section>

<!-- Signup Section -->
<section id="signUp" class="signup-section">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-lg-8 mx-auto text-center">

        <h2 class="mb-5 text-white">Créez un compte pour retrouver vos recherches favorites.</h2>
          <a class="btn btn-primary text-white mx-auto" href="{{ url_for('main.register') }}">S'inscrire</a>
      </div>
    </div>
  </div>
</section>


  </div>

{% endblock %}

app/templates/legal.html
{% extends 'base.html' %}

{% block content %}

<header class="standard-header">
	<div class="container">
		
	</div>
</header>

<section class="my-auto" id="legal">
  <div class="container text-center mt-2 pt-5">

	<h2><u>Informations générales</u></h2>
	<p>Conception : <a href="https://www.linkedin.com/in/ronan-le-hay-3bb64b14a/"></a>Ronan LE HAY</p>
	<p>Thème utilisé : <a href="https://startbootstrap.com/template-overviews/grayscale/">Grayscale</a>.</p>
	<p>Hébergement : <a href="https://www.heroku.com/">Heroku</a>.</p>
	<hr width="50%"></hr>
	<h2><u>Données utilisées</u></h2>
	<h3>Météo</h3>
	<p>Les données météorologiques utilisées par FishingDay proviennet du site <a href="https://openweathermap.org/">OpenWeatherMap</a>.</p>
	<h3>Horaires des marées</h3>
	<p>Le calcul des horaires des marées est effectué par le site <a href="https://www.worldtides.info/">WorldTides</a>.</p>
	<h3>Carte des fonds</h3>
	<p>La carte marine affichée est fournie par le site <a href="https://www.navionics.com">Navionics</a>.</p>
  	<h3>Carte des lieux</h3>
  	<p>La carte récapitulatives des recherches utiliseurs est générée à l'aide de l'api <a href="https://cloud.google.com/maps-platform/?hl=fr">Google Maps</a>.</p>
  </div>



</section>

{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}

<header class="standard-header">
	<div class="container">
		
	</div>
</header>

<section class="" id="login">
  <div class="container text-center mt-2 pt-5">

  	<h1>Connexion</h1>
  	  {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
          <p class="form-error mx-auto">{{ message }}</p>
          {% endfor %}
        {% endif %}
      {% endwith %}
  	  <form class="col-lg-5 col-md-6 mx-auto" action="" method="post" novalidate>
  			{{ form.hidden_tag() }}
  			<p>
  				{{ form.email.label }}<br>
  				{{ form.email(class="form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0", placeholder="exemple@email.com") }}
  			</p>
  			<p>
  				{{ form.password.label }}<br>
  				{{ form.password(class="form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0", placeholder="********") }}
  			</p>
  			<p>
  				{{ form.remember_me() }} {{ form.remember_me.label }}
  			</p>
  			<p>{{ form.submit() }}</p>
  	  </form>

  </div>
</section>

{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% block content %}

<header class="standard-header">
	<div class="container">
		
	</div>
</header>

<section class="" id="resgister">
  <div class="container text-center mt-2 pt-5">

  	<h1>Inscription</h1>
  	  {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
          <p class="form-error mx-auto">{{ message }}</p>
          {% endfor %}
        {% endif %}
      {% endwith %}
  	  <form class="col-lg-5 col-md-6 mx-auto" action="" method="post" novalidate>
  			{{ form.hidden_tag() }}
        <p>
          {{ form.username.label }}<br>
          {{ form.username(class="form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0", placeholder="Toto") }}
        </p>
        <p>
  				{{ form.email.label }}<br>
  				{{ form.email(class="form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0", placeholder="Toto@email.com") }}
  			</p>
  			<p>  
  				{{ form.password.label }}<br>
  				{{ form.password(class="form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0", placeholder="********") }}
  			</p>
        <p>
          {{ form.password_confirm.label }}<br>
          {{ form.password_confirm(class="form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0", placeholder="********") }}
        </p>
  			<p>{{ form.submit() }}</p>
  	  </form>

  </div>
</section>

{% endblock %}